### ISSUE TITLE
Two builds per PR on Codeship

### ISSUE THREAD

**Issue by pwim** [deppbot/feedback#5]
I think this is the same issue as #1, though I don't see any way of working around it on Codeship.

As far as I understand it, when deppbot makes a PR it
1. Pushes a new branch of the format `bundle-update-2016-06-14-201137`
2. Pushes a new commit to that branch
3. Makes a PR

The way Codeship is working, both step 1 & step 2 trigger a build.

Normally when I'm doing development, I create a branch locally, commit to that branch, and then push, resulting in only one build. It seems to me that deppbot could do the same thing, but I guess you have a good reason for doing it the current way.

This isn't a big deal, as I can manually cancel the extra build, but it would be nice if it was handled a bit smoother.

**Comment by JuanitoFatas** [comment]
Hi Paul,

Thanks for the feedback and sorry for the troubles there.

I'll look into this.
