### ISSUE TITLE
I can't see your site

### ISSUE THREAD

**Issue by tmd45** [deppbot/feedback#9]
The site, https://www.deppbot.com/ is `502 Bad Gateway`. 😱 
Have you noticed..?

**Comment by winston** [comment]
Fixed. Sorry for the inconvenience!

**Comment by shinnn** [comment]
@winston @JuanitoFatas It responds with 502 again now (Mon, 21 Aug 2017 08:20:09 GMT).

**Comment by shinnn** [comment]
https://www.deppbot.com/ is back (Tue, 22 Aug 2017 05:03:11 GMT). However, you should notify users by e-mail or [Twitter](https://twitter.com/deppbot) every time the service is down or launch a status page like [status.github.com](https://status.github.com/). 

@winston @JuanitoFatas Please be aware that you're managing a fee‐based service, not a personal hobby.

**Comment by fukayatsu** [comment]
> The site, https://www.deppbot.com/ is 502 Bad Gateway. 😱

@winston It's 502 again? 😢

**Comment by fukayatsu** [comment]
I confirmed that it has been fixed 👍
